### ISSUE TITLE
Add user following support.

### ISSUE THREAD

**Issue by kxxoling** [azu/gitbook-plugin-github-buttons#12]
I want to add a user following button laying beside project starring button. As https://ghbtns.com/ also supports user following button, I think it could be implemented. Would you like to add this functionality to your plugin?

**Comment by azu** [comment]
Yes. It seem reasonable to me.
Welcome to pull-request.

- [x] Add `user` option
- [ ] Maybe Add `gitbook` field to pacakge.json to work current gitbook
  - [Create a plugin · GitBook Toolchain Documentation](https://toolchain.gitbook.com/plugins/create.html "Create a plugin · GitBook Toolchain Documentation")

**Comment by kxxoling** [comment]
But there's some problem with the configure options used now to support user following. Maybe it's better to change it from:

```json
"github-buttons": {
  "repo": "azu/JavaScript-Plugin-Architecture",
  "types": [
    "star",
    "watch"
  ],
  "size": "large"
}
```
to:

```json
"github-buttons": [{
  "repo": "azu/JavaScript-Plugin-Architecture",
  "type":  "watch",
  "size": "large"
}, {
  "repo": "azu/JavaScript-Plugin-Architecture",
  "type":  "star",
  "size": "large"
}, {
  "user": "azu",
  "size": "large"
}]
```

**Comment by azu** [comment]
Thanks for suggestion.
Ok. I see.
We neet to do breaking change.

```json
"github-buttons": [{
  "repo": "azu/JavaScript-Plugin-Architecture",
  "type":  "watch",
  "size": "large"
}, {
  "repo": "azu/JavaScript-Plugin-Architecture",
  "type":  "star",
  "size": "large"
}, {
  "user": "azu",
  "type": "follow",
  "size": "large",
  "count": true
}]
```

**Comment by azu** [comment]
Type interface of the option:

```ts
{
  repo?: string;
  type: "watch" | "star" | "fork" | "follow";
  size?: "large";
  count?: boolean;
  // plugin extension
  width?: number;
  height?: number;
}[]
```

**Comment by kxxoling** [comment]
It seems GitBook doesn't support Array as plugin config, but I did not find any explanation about that. So I tried this:

```json
    "github-buttons": {
      "buttons": [{
        "user": "kxxoling",
        "type": "follow",
        "size": "large"
      }]
    },
```

And almost finished now.

**Comment by azu** [comment]
Merge #13 and Release https://github.com/azu/gitbook-plugin-github-buttons/releases/tag/3.0.0
Thanks to @kxxoling 

@kxxoling I've added you as collaborator. Thanks again!
