### ISSUE TITLE
it does not work for gitbook   3.1.1

### ISSUE THREAD

**Issue by snowdream** [azu/gitbook-plugin-github-buttons#3]
https://www.npmjs.com/package/gitbook  3.1.1

**Comment by twang2218** [comment]
@snowdream What's the problem exactly? I'm using 3.2.2 on my laptop, it seems fine.

```bash
$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
```

**Comment by azu** [comment]
Release [2.1.0](https://github.com/azu/gitbook-plugin-github-buttons/releases/tag/2.1.0 "2.1.0").
